POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "Account": "abc13",
  "Password": "abc123"
}

###

POST http://localhost:8081/api/auth/signin
Content-Type: application/json

{
  "Device": 1,
  "Account": "abc",
  "Password": "abc"
}

