@startuml
'!theme amiga
!theme blueprint
'!theme plain
'!theme crt-green
'!theme united

'https://plantuml.com/sequence-diagram

title 发送消息流程

actor 用户A as userA
actor 用户B as userB

participant "Server" as server

autonumber

userA -> server: Authentication Request
activate server
server -> userB:do somthing
deactivate server
userA --> userB: Authentication Response

userA -> userB: Another authentication Request
userB <-- userA: another authentication Response

@enduml