[ApiHttp]
Addr = "0.0.0.0"
Port = 8081

[WsServer]
Addr = "0.0.0.0"
Port = 8080

[IMService]
# IM 服务的地址
Service = "127.0.0.1:8080"
Addr = "0.0.0.0"
Port = 8081

[MySql]
Host = "dengzii.com"
Port = 3306
Username = "go_im_test"
Password = "8dmaRNCYBFHP4F67"
Db = "go_im_test"
Charset = "utf8mb4"

[Redis]
Host = "dengzii.com"
Port = 6378
Password = "tcmm1713."
Db = 9