[ApiHttp]
Addr = "0.0.0.0"
Port = 8081

[WsServer]
Addr = "0.0.0.0"
Port = 8080

[IMRpcServer]
Addr = "127.0.0.1"
Port = 8090
Etcd = []
Name = "im_rpc_service"

[MySql]
Host = "127.0.0.1"
Port = 3306
Username = "root"
Password = "root"
Db = "go_im"
Charset = "utf8mb4"

[Redis]
Host = "127.0.0.1"
Port = 6379
Password = ""
Db = 8