[ApiHttp]
Addr = "0.0.0.0"
Port = 8081

[IMService]
Service = "192.168.1.123:8080"
Addr = "0.0.0.0"
Port = 8080

[MySql]
Host = "127.0.0.1"
Port = 3306
Username = "root"
Password = "root"
Db = "go_im"
Charset = "utf8mb4"

[Redis]
Host = "127.0.0.1"
Port = 6379
Password = ""
Db = 8