@startmindmap
'https://plantuml.com/mindmap-diagram

title 功能大纲

* IM

** 认证
    *** 注册
    *** 密码登录
    *** Token登录
    *** 退出登录
    *** 更新密码
** 用户
    *** 用户消息
        **** 获取自己的信息
        **** 获取好友信息
        **** 获取非好友信息
    *** 更新个人信息

** 聊天
    *** 方式
        **** 一对一聊天
        **** 多对多聊天
        **** 多人聊天
    *** 历史记录
        **** 查询一段时间内的记录
        **** 按时间和数量分页
    *** 消息记录同步

left side

** 好友
    *** 添加好友
    *** 删除好友
    *** 好友请求操作
** 群
    *** 管理
        **** 设置管理员
        **** 取消管理员
        **** 删除群成员
        **** 加群请求操作
    *** 创建群
    *** 离开群
    *** 加入群
    *** 邀请群成员
** app
    *** 获取通知列表
@endmindmap
