@startmindmap
'https://plantuml.com/mindmap-diagram

title My super title

* <&flag>消息
    ** 可靠性
        *** 上线同步离线
        *** 离线推送
        *** 收发ACK机制
        *** 客户端超时重发
        *** 发送方会话发送Seq判断兜底
        *** 消息Seq连续性判断再次兜底
    ** 有序性
        *** 收发一致性
            **** 发送方发送 seq
        *** 整体有序性
            **** 接收方全局接收 seq
        *** 群消息排序
            **** 根据群消息 seq
    ** 投递方式
        *** 推送
            **** 默认方式
        *** 拉取
            **** 网络较差
            **** 传输频率大
    ** 存储
        *** 所有消息每个用户存一份
        *** x 缓存一定时间内的离线消息
        *** x 冷热分离

@endmindmap
