@startmindmap
'https://plantuml.com/mindmap-diagram

* <&flag>消息

** 消息 ID
    *** 由客户端生成
    *** 按时间单调递增全局唯一
    *** 可用于排序
** 存储
    *** 所有消息都每个用户存一份(写扩散)
    *** 缓存一定时间内的离线消息
    *** 冷热分离
** 可靠性
    *** 上线同步离线
    *** 离线推送
    *** 收发ACK机制
    *** 客户端超时重发
    *** 发送方会话发送Seq判断兜底
    *** 消息Seq连续性判断再次兜底

left side

** 有序性
    *** 收发一致性
        **** 发送消息上一条消息 seq+1
        **** 发送方消息 ID 排序
        **** 发送方发送 seq
    *** 整体有序性
    *** 群消息排序
        **** 群每次下发一条消息群消息 seq+1
        **** 根据群消息 seq
** 投递方式
    *** 推送
        **** 人数较少的群
        **** 单聊, 实时性较高
    *** 拉取
        **** 大群聊使用, 服务端控制推送频率
        **** 网络较差或传输频率大
** 消息同步
    *** 登录后上传本地全局 seq 同步
    *** 客户端收到消息对比本地全局seq大则拉取
    *** 群聊 seq 对比服务端最新 seq 拉取

@endmindmap
