@startuml
'https://plantuml.com/activity-diagram-beta

card User {
    class user_info {
        *uid int64
        nickname string
        password string
        state int64
        avatar string
        register_at time
    }
    class user_token <<Redis>>{
        uid_device string
        token string
    }
    class user_auth_info <<Redis_Map>>{
       uid string

       info auth_info
    }
    class auth_info<<Redis_Map_Field>>{
        device int
        token string
        appId int
    }
    user_info::uid-->user_auth_info::uid
    user_info::uid-->user_token::uid
    user_auth_info::info-->auth_info
}

card Group {
    class group_info {
        *gid int64
        members int64
        avatar string
        mute int64
        flag int64
        create_at time
    }
    class group_member{
        gid int64
        uid int64
        flag int64
        last_ack_mid int64
        last_ack_seq int64
    }
    group_info::gid-->group_member::gid
}


@enduml
